version: '3.8'

services:
  mysql:
    container_name: spring-boot-3-mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: identity_service
    ports:
      - "13306:3306"
    volumes:
      - ./data:/var/lib/mysql

volumes:
  data:
    driver: local