server:
  port: 8070
  servlet:
    context-path: /identity

spring:
  datasource:
    url: jdbc:mysql://localhost:13306/identity_service
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "gTWFWOUfj5ujOpkXxZziYEC0r6tiyvasmwjicIZ6ER+pTMk3gFk2Uljx7tztIh0y"
  expiration: 10 # In seconds
  refresh-expiration: 30 # In seconds