server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/identity_service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "gTWFWOUfj5ujOpkXxZziYEC0r6tiyvasmwjicIZ6ER+pTMk3gFk2Uljx7tztIh0y"
  tokens:
    adminToken: "Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsInNjb3BlIjoiUk9MRV9BRE1JTiBSRUpFQ1RfUE9TVCBBUFBST1ZFX1BPU1QgQ1JFQVRFX1BPU1QiLCJpc3MiOiJmcmFua3RyYW52YW50dS5jb20iLCJleHAiOjE3MTQ1ODIwODYsImlhdCI6MTcxNDU3ODQ4NiwianRpIjoiZGFmZTFkMjgtNzk1Yy00YWYwLTllMzctYTdiODQzZmQ0MjdkIn0.L17FgIVA5AQ-F-z8qEt3yYrqc5sK1kLt93jPsI4MnqE4QIzbGZzCtiVpTUN9_VEo3Tqpsd9gVAja7kG27qumsQ"
    user1Token: "Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyMSIsInNjb3BlIjoiUk9MRV9VU0VSIENSRUFURV9QT1NUIiwiaXNzIjoiZnJhbmt0cmFudmFudHUuY29tIiwiZXhwIjoxNzE0NTgyMDcxLCJpYXQiOjE3MTQ1Nzg0NzEsImp0aSI6IjYwN2I0ZTQwLTc1MTItNDlkZS04M2YyLWQ0ZTVhNGNiMjdkNSJ9.KgXTkkjHspIvJ5-uHCxPbC-XN5RzFNlnIWI80qXqAm7SGrDz84Z0Ph2_OMoyyu0CTRE0BrrK3CHaiJwcnlLleA"
    user2Token: "Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyMiIsInNjb3BlIjoiUk9MRV9VU0VSIENSRUFURV9QT1NUIiwiaXNzIjoiZnJhbmt0cmFudmFudHUuY29tIiwiZXhwIjoxNzE0NTgxOTM4LCJpYXQiOjE3MTQ1NzgzMzgsImp0aSI6IjdkNzM0MDdmLTQ0MTItNGU5NS1iZDNiLWVkMzc5MmUyODJiZiJ9.v1azUHst77XYN39xnNM_Q8MsoEgTqGwqmqv2Aerhv80hyvlJci7XTEXXkrEAih27TTeetbuotS884pxzs4FQMw"
    invalidToken: "Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyIiwic2NvcGUiOiJST0xFX1VTRVIgQ1JFQVRFX1BPU1QiLCJpc3MiOiJmcmFua3RyYW52YW50dS5jb20iLCJleHAiOjE3MTQ1ODE5MzgsImlhdCI6MTcxNDU3ODMzOCwianRpIjoiN2Q3MzQwN2YtNDQxMi00ZTk1LWJkM2ItZWQzNzkyZTI4MmJmIn0.yjgyijPnHXgTqTazldP74EvN9TwxDWqYSyIGCbsoNqxGxy4PeiibBva4D9P-PY-7XzT3tkHXJOeqZw6LuGziTw"
params:
  user1Id: "95b81180-10db-4994-aa2b-4ccbdbdc6af7"
  user2Id: "75707056-0ab2-45d2-a912-5e15f068c94a"